import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import AppContextWrapper from "@/context/AuthContext";
import { ToastContainer } from "react-toastify";
import PostContextWrapper from "@/context/PostsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blue Banana Test",
  description: "Generated by Blue banana",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextWrapper>
          <PostContextWrapper>
            <ToastContainer theme="light" autoClose={3000} />
            {children}
          </PostContextWrapper>
        </AppContextWrapper>
      </body>
    </html>
  );
}
